--skip-ci compile change

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -40,7 +40,7 @@ TESSERACT_DIR="$BASE_DIR"/tesseract
 
 LIBJPEG_VERSION=9b
 ZLIB_VERSION=1.2.11
-LIBPNG_VERSION=1.6.34
+LIBPNG_VERSION=1.6.27
 LIBTIFF_VERSION=4.0.9
 LEPTONICA_VERSION=1.74.4
 TESSERACT_VERSION=3.05.01
@@ -88,8 +88,8 @@ then
         rm -rf $SRC_DIR/jpeg* $BUILD_DIR/jpeg*
 
         if [ ! -f $ARCHIVE_DIR/jpegsrc.v$LIBJPEG_VERSION.tar.gz ]; then
-                #Download the file
-                curl -o $ARCHIVE_DIR/jpeg.v$LIBJPEG_VERSION.tar.gz http://www.ijg.org/files/jpegsrc.v$LIBJPEG_VERSION.tar.gz
+			#Download the file
+			curl -o $ARCHIVE_DIR/jpeg.v$LIBJPEG_VERSION.tar.gz http://www.ijg.org/files/jpegsrc.v$LIBJPEG_VERSION.tar.gz
         fi
 
         echo "Extracting archive"
@@ -98,7 +98,7 @@ then
         cd $SRC_DIR/jpeg-$LIBJPEG_VERSION
 
         echo "Configuring Lib Jpeg for Standalone"
-        ./configure --prefix=$BUILD_DIR
+        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib" CPPFLAGS="-I$BUILD_DIR/include"
 
         echo "Building LIBJPEG and deploying to "
         echo "    -> $BUILD_DIR"
@@ -106,10 +106,10 @@ then
 
         #Check if the build was successful
         if [ -f $BUILD_DIR/include/jpeglib.h ]; then 
-                echo "LIB JPEG Build Successful"
+			echo "LIB JPEG Build Successful"
         else
-                echo "LIBJPEG build failed. Exiting."
-                exit 1
+			echo "LIBJPEG build failed. Exiting."
+			exit 1
         fi
 else
         echo "Skipping LIBJPEG"
@@ -126,8 +126,8 @@ then
         rm -rf $SRC_DIR/zlib* $BUILD_DIR/zlib*
 
         if [ ! -f $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz ]; then
-                #Download the file
-                curl -o $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz http://zlib.net/fossils/zlib-$ZLIB_VERSION.tar.gz
+			#Download the file
+			curl -o $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz http://zlib.net/fossils/zlib-$ZLIB_VERSION.tar.gz
         fi
 
         echo "Extracting archive"
@@ -136,19 +136,24 @@ then
         cd $SRC_DIR/zlib-$ZLIB_VERSION
 
         echo "Configuring ZLIB for Standalone"
-        ./configure --solo --static
+        ./configure --prefix=$BUILD_DIR
 
         echo "Building Zlib and deploying to "
         echo "    -> $BUILD_DIR"
-        make install prefix=$BUILD_DIR
+        make check
+        make install
 
         #Check if the build was successful
         if [ -f $BUILD_DIR/include/zlib.h ]; then 
-                echo "ZLIB Build Successful"
+			echo "ZLIB Build Successful"
         else
-                echo "ZLIB build failed. Exiting."
-                exit 1
+			echo "ZLIB build failed. Exiting."
+			exit 1
         fi
+
+		echo "Exporting lib path to pkg_config_path"
+		export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$BUILD_DIR/lib/pkgconfig:$BUILD_DIR/lib
+
 else
         echo "Skipping ZLib"
 fi
@@ -163,8 +168,8 @@ then
         rm -rf $SRC_DIR/libpng* $BUILD_DIR/libpng*
 
         if [ ! -f "$ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz" ]; then
-                #Download the file
-                curl -L -o $ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz http://downloads.sourceforge.net/project/libpng/libpng16/$LIBPNG_VERSION/libpng-$LIBPNG_VERSION.tar.gz?use_mirror=excellmedia
+			#Download the file
+			curl -L -o $ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz http://downloads.sourceforge.net/project/libpng/libpng16/older-releases/$LIBPNG_VERSION/libpng-$LIBPNG_VERSION.tar.gz?use_mirror=excellmedia
         fi
 
         echo "Extracting archive"
@@ -177,7 +182,7 @@ then
         cp $BUILD_DIR/include/zconf.h .
 
         echo "Configuring Lib PNG for Standalone"
-        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib -lz"
+        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib" CPPFLAGS="-I$BUILD_DIR/include"
 
         echo "Building LIBPNG and deploying to $BUILD_DIR"
         make check
@@ -185,10 +190,10 @@ then
 
         #Check if the build was successful
         if [ -f "$BUILD_DIR/include/libpng16/png.h" ]; then 
-                echo "LIB PNG Build Successful"
+			echo "LIB PNG Build Successful"
         else
-                echo "LIBPNG build failed. Exiting."
-                exit 1
+			echo "LIBPNG build failed. Exiting."
+			exit 1
         fi
 
 else
@@ -206,8 +211,8 @@ then
         rm -rf $SRC_DIR/tiff* $BUILD_DIR/tiff*
 
         if [ ! -f $ARCHIVE_DIR/jpegsrc.v$LIBTIFF_VERSION.tar.gz ]; then
-                #Download the file
-                curl -o $ARCHIVE_DIR/tiff-$LIBTIFF_VERSION.tar.gz http://download.osgeo.org/libtiff/tiff-$LIBTIFF_VERSION.tar.gz
+			#Download the file
+			curl -o $ARCHIVE_DIR/tiff-$LIBTIFF_VERSION.tar.gz http://download.osgeo.org/libtiff/tiff-$LIBTIFF_VERSION.tar.gz
         fi
 
         echo "Extracting archive"
@@ -216,7 +221,7 @@ then
         cd $SRC_DIR/tiff-$LIBTIFF_VERSION
 
         echo "Configuring Lib Tiff for Standalone"
-        ./configure --prefix=$BUILD_DIR
+        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib" CPPFLAGS="-I$BUILD_DIR/include"
 
         echo "Building LIBTIFF and deploying to "
         echo "    -> $BUILD_DIR"
@@ -224,10 +229,10 @@ then
 
         #Check if the build was successful
         if [ -f $BUILD_DIR/include/tiff.h ]; then 
-                echo "LIB TIFF Build Successful"
+			echo "LIB TIFF Build Successful"
         else
-                echo "LIBTIFF build failed. Exiting."
-                exit 1
+			echo "LIBTIFF build failed. Exiting."
+			exit 1
         fi
 else
         echo "Skipping LIBTIFF"
@@ -243,11 +248,9 @@ then
         rm -rf $SRC_DIR/leptonica* $BUILD_DIR/leptonica*
 
         if [ ! -f $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz ]; then
-                #Download the file
-                curl -o $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz http://www.leptonica.com/source/leptonica-$LEPTONICA_VERSION.tar.gz
+			#Download the file
+			curl -o $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz http://www.leptonica.com/source/leptonica-$LEPTONICA_VERSION.tar.gz
         fi
-
-		export LD_LIBRARY_PATH="-L$BUILD_DIR/lib"
 
         echo "Extracting archive"
         tar -xzf $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz -C $SRC_DIR
@@ -255,38 +258,32 @@ then
         cd $SRC_DIR/leptonica-$LEPTONICA_VERSION
         
         echo "Configuring leptonica for standalone"
-        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib" CPPFLAGS="-I$BUILD_DIR/include"
+        ./configure --prefix=$BUILD_DIR LDFLAGS="-L$BUILD_DIR/lib" CPPFLAGS="-lz -lpng -ljpeg -ltiff -lpthread"
 		
         echo "Building LEPTONICA and deploying to "
         echo "    -> $BUILD_DIR"
-		make EXTRAINCLUDES="-I./include -I./include/libpng16"
+		make EXTRAINCLUDES="-I$BUILD_DIR/include"
 
 
         #Check if the build was successful
         if [ -f $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/.libs/liblept.a ]; then 
-                echo "Leptonica Build Successful"
+			echo "Leptonica Build Successful"
         else
-                echo "LEPTONICA build failed. Exiting."
-                exit 1
+			echo "LEPTONICA build failed. Exiting."
+			exit 1
         fi
 
         echo "Copying files for Tesseract"
-        cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/.libs/liblept.a $BUILD_DIR/lib
+        # cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/.libs/liblept.a $BUILD_DIR/lib
 
         if [ ! -f $BUILD_DIR/include/leptonica ]; then
-                mkdir $BUILD_DIR/include/leptonica
+			mkdir $BUILD_DIR/include/leptonica
         fi
 
         cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/*.h $BUILD_DIR/include/leptonica
 
 		echo "Copying lept.pc to pkgconfig"
 		cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/lept.pc $BUILD_DIR/lib/pkgconfig
-
-		echo "Exporting lib leptonica to pkg_config_path"
-		export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$BUILD_DIR/lib/pkgconfig:$BUILD_DIR/lib
-
-		# pkg-config --cflags lept
-		# pkg-config --libs lept
 
 else
         echo "Skipping Leptonica"
@@ -302,36 +299,32 @@ then
 
         #Create Tesseract Build Directory
         if [ ! -d $TESSERACT_DIR ]; then
-                mkdir $TESSERACT_DIR
+			mkdir $TESSERACT_DIR
         else
-                rm -rf $TESSERACT_DIR/*
+			rm -rf $TESSERACT_DIR/*
         fi
 
-        # if [ ! -f $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz ]; then
-		# 		#Download the file
-        #        	curl -L -o $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz https://github.com/tesseract-ocr/tesseract/archive/$TESSERACT_VERSION.tar.gz
-       	# fi
+        if [ ! -f $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz ]; then
+			#Download the file
+			curl -L -o $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz https://github.com/tesseract-ocr/tesseract/archive/$TESSERACT_VERSION.tar.gz
+       	fi
  
        	echo "Extracting archive"
-    	# tar -xzf $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz -C $SRC_DIR
-		cp -r $BASE_DIR/../tesseract $SRC_DIR
-      
-        cd $SRC_DIR/tesseract
-
-        cp -r $BUILD_DIR/include src
-        cp -r $BUILD_DIR/bin src
-        cp -r $BUILD_DIR/lib src
+    	tar -xzf $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz -C $SRC_DIR
+		      
+        cd $SRC_DIR/tesseract-$TESSERACT_VERSION
         
         echo "Running autogen"
         ./autogen.sh || bail_out
 
-		export CXXFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16 -I$BUILD_DIR/include/leptonica -lpng -ljpeg -ltiff -lz"
-        export CPPFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16 -I$BUILD_DIR/include/leptonica -lpng -ljpeg -ltiff -lz"
+		export CXXFLAGS="-llept -lz -lpng -ljpeg -ltiff -lpthread"
+        export CPPFLAGS="-llept -lz -lpng -ljpeg -ltiff -lpthread"
         export LDFLAGS="-L$BUILD_DIR/lib"
-        export LIBLEPT_HEADERSDIR=$BUILD_DIR/include/leptonica
+		export LIBLEPT_HEADERSDIR=$BUILD_DIR/include/leptonica
+		export LD_LIBRARY_PATH=$BUILD_DIR/lib
         
 		echo "Configuring Tesseract"
-        ./configure --prefix=$TESSERACT_DIR --with-extra-includes=$BUILD_DIR/include --with-extra-libraries=$BUILD_DIR/lib || bail_out
+        ./configure --prefix=$TESSERACT_DIR || bail_out
 
         echo "Start Building Tesseract"
         make
@@ -339,28 +332,28 @@ then
         ls $TESSERACT_DIR/bin
 
         if [ -x $TESSERACT_DIR/bin/tesseract ]; then
-                echo "Tesseract Build Successful"
+			echo "Tesseract Build Successful"
         else
-                echo "Tesseract build failed. Exiting."
-                exit 1
+			echo "Tesseract build failed. Exiting."
+			exit 1
         fi
 
         echo "Checking the language files"
         if [ ! -f "$ARCHIVE_DIR/eng.traineddata" ]; then
-                #Download the file
-                curl -L -o $ARCHIVE_DIR/eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
+			#Download the file
+			curl -L -o $ARCHIVE_DIR/eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
         fi
 
         echo "Checking OSD (Optical Script Detection) models"
         if [ ! -f "$ARCHIVE_DIR/osd.traineddata" ]; then
-                #Download the file
-                curl -L -o $ARCHIVE_DIR/osd.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/osd.traineddata
+			#Download the file
+			curl -L -o $ARCHIVE_DIR/osd.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/osd.traineddata
         fi
 
 		echo "Checking MD (Math / equation detection) models"
 		if [ ! -f "$ARCHIVE_DIR/eq.traineddata" ]; then
-                #Download the file
-                curl -L -o $ARCHIVE_DIR/eq.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/equ.traineddata
+			#Download the file
+			curl -L -o $ARCHIVE_DIR/eq.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/equ.traineddata
         fi
 
         echo "Installing Languages, OSD and MD"
